server:
  port: 9000
  error:
    includeMessage: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plansail
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG